"""edit post table

Revision ID: 7ac2a4fba051
Revises: bcaa2576776a
Create Date: 2019-02-18 04:34:59.966977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac2a4fba051'
down_revision = 'bcaa2576776a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_Category'), 'category', ['Category'], unique=True)
    op.drop_index('ix_category_Category', table_name='category')
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('content', sa.String(length=140), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=50), nullable=True))
    op.drop_constraint('post_user_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    op.drop_column('post', 'body')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_user_id_fkey', 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'title')
    op.drop_column('post', 'content')
    op.drop_column('post', 'author_id')
    op.create_index('ix_category_Category', 'category', ['Category'], unique=True)
    op.drop_index(op.f('ix_category_Category'), table_name='category')
    # ### end Alembic commands ###
